In [ ]:
import csv
import numpy as np

filename = "/content/testmarks 3.csv"
data = []

with open(filename, "r") as file:
    csv_reader = csv.reader(file)
    next(csv_reader)

    for row in csv_reader:
        data.append(row[1:])

matrix = np.array(data, dtype=float)

print("Matrix of marks for each student:")
print(matrix)



#Mean of every subject marks
mean = np.mean(matrix, axis=0)
print(" SIC AM FE IC :")
print(mean)



#Totyal marks of each student
row_sum = np.sum(matrix, axis=1)
print("Total marks of each student:")
print(row_sum)


# dividing matrix for each roll no

matrix_801 = matrix[:1, :]

print("801:")
print(matrix_801)


matrix_802 = matrix[1:2, :]

print("802:")
print(matrix_802)


matrix_803 = matrix[2:3, :]

print("803:")
print(matrix_803)


matrix_804 = matrix[3:4, :]

print("804:")
print(matrix_804)



#stacking
#horizantal staking
re_array=np.hstack((matrix_801,matrix_802))
print("Horizantal staked matrix is:")
print(re_array)

#vertical staking 1
arr_801_802=np.vstack((matrix_801,matrix_802))
print("Vertical staked matrix 1 is:")
print(arr_801_802)

#vertical staking 2
arr_803_804=np.vstack((matrix_803,matrix_804))
print("Vertical staked matrix 2 is:")
print(arr_803_804)



#Addition of two matrix
addition=arr_801_802+arr_803_804
print("Addition of two matrix")
print(addition)


#Subtraction of two matrix
subtraction=arr_801_802-arr_803_804
print("Subtraction of two matrix")
print(subtraction)

# Multiplication (element-wise)
multiplication = arr_801_802 * arr_803_804
print("Multiplication (element-wise) is:")
print(multiplication)




# Mean along the columns
mean_columns = np.mean(matrix, axis=0)
print("Mean along columns:")
print(mean_columns)

# Mean along the rows
mean_rows = np.mean(matrix, axis=1)
print("Mean along rows:")
print(mean_rows)

# Standard deviation along the columns
std_columns = np.std(matrix, axis=0)
print("Standard deviation along columns:")
print(std_columns)

# Standard deviation along the rows
std_rows = np.std(matrix, axis=1)
print("Standard deviation along rows:")
print(std_rows)

# Minimum value along the columns
min_columns = np.min(matrix, axis=0)
print("Minimum value along columns:")
print(min_columns)

# Minimum value along the rows
min_rows = np.min(matrix, axis=1)
print("Minimum value along rows:")
print(min_rows)

# Maximum value along the columns
max_columns = np.max(matrix, axis=0)
print("Maximum value along columns:")
print(max_columns)

# Maximum value along the rows
max_rows = np.max(matrix, axis=1)
print("Maximum value along rows:")
print(max_rows)

# Sum along the columns
sum_columns = np.sum(matrix, axis=0)
print("Sum along columns:")
print(sum_columns)

# Sum along the rows
sum_rows = np.sum(matrix, axis=1)
print("Sum along rows:")
print(sum_rows)




# Matrix addition
addition = matrix + 50
print("Matrix Addition:")
print(addition)

# Matrix subtraction
subtraction = matrix - 50
print("Matrix Subtraction:")
print(subtraction)


# Matrix multiplication
multi = matrix * 2
print("multiplication:")
print(multi)

# Matrix division
divi= matrix / 2
print(" Division:")
print(divi)


# Bitwise AND operation
bitwise_and = np.bitwise_and(matrix, 10)
print("Bitwise AND:")
print(bitwise_and)

# Bitwise OR operation
bitwise_or = np.bitwise_or(matrix, 10)
print("Bitwise OR:")
print(bitwise_or)

# Bitwise XOR operation
bitwise_xor = np.bitwise_xor(matrix, 10)
print("Bitwise XOR:")
print(bitwise_xor)

# Bitwise NOT operation
bitwise_not = np.bitwise_not(matrix)
print("Bitwise NOT:")
print(bitwise_not)

Matrix of marks for each student:
[[28.48 34.18 30.56 22.23]
 [28.1  33.72 30.68 22.82]
 [26.16 31.39 28.2  22.53]
 [26.16 31.39 28.78 20.93]
 [26.1  31.32 28.22 20.82]
 [25.45 30.54 27.73 21.05]
 [26.16 31.39 28.01 20.51]
 [27.44 32.93 28.83 22.08]
 [28.63 34.35 31.03 22.68]
 [30.35 36.42 31.38 23.1 ]]
 SIC AM FE IC :
[27.303 32.763 29.342 21.875]
Total marks of each student:
[115.45 115.32 108.28 107.26 106.46 104.77 106.07 111.28 116.69 121.25]
801:
[[28.48 34.18 30.56 22.23]]
802:
[[28.1  33.72 30.68 22.82]]
803:
[[26.16 31.39 28.2  22.53]]
804:
[[26.16 31.39 28.78 20.93]]
Horizantal staked matrix is:
[[28.48 34.18 30.56 22.23 28.1  33.72 30.68 22.82]]
Vertical staked matrix 1 is:
[[28.48 34.18 30.56 22.23]
 [28.1  33.72 30.68 22.82]]
Vertical staked matrix 2 is:
[[26.16 31.39 28.2  22.53]
 [26.16 31.39 28.78 20.93]]
Addition of two matrix
[[54.64 65.57 58.76 44.76]
 [54.26 65.11 59.46 43.75]]
Subtraction of two matrix
[[ 2.32  2.79  2.36 -0.3 ]
 [ 1.94  2.33  1.9   1.89]]
Multipli

TypeError: ignored

In [ ]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('/content/testmarks 3.csv')



# Assuming you have a dataset stored in a pandas DataFrame
df = pd.DataFrame(dataset)

# Convert 'RollNo' column into a list
Rollno_list = df['RollNo'].tolist()

# Convert 'SIC' column into a list
SIC_list = df['SIC'].tolist()

#Convert 'AM' column into a list
AM_list = df['AM'].tolist()

#Convert 'FE' column into a list
FE_list = df['FE'].tolist()

#Convert 'ic' column into a list
IC_list = df['IC'].tolist()



# Print the converted lists
print(Rollno_list)
print(SIC_list)
print(AM_list)
print(FE_list)
print(IC_list)


[801, 802, 803, 804, 805, 806, 807, 808, 809, 810]
[28.48, 28.1, 26.16, 26.16, 26.1, 25.45, 26.16, 27.44, 28.63, 30.35]
[34.18, 33.72, 31.39, 31.39, 31.32, 30.54, 31.39, 32.93, 34.35, 36.42]
[30.56, 30.68, 28.2, 28.78, 28.22, 27.73, 28.01, 28.83, 31.03, 31.38]
[22.23, 22.82, 22.53, 20.93, 20.82, 21.05, 20.51, 22.08, 22.68, 23.1]


In [ ]:
import numpy as np
import pandas as pd

# Create a dictionary with the given data
data = {
    'RollNo': [801, 802, 803, 804, 805, 806, 807, 808, 809, 810],
    'SIC': [28.48, 28.1, 26.16, 26.16, 26.1, 25.45, 26.16, 27.44, 28.63, 30.35],
    'AM': [34.18, 33.72, 31.39, 31.39, 31.32, 30.54, 31.39, 32.93, 34.35, 36.42],
    'FE': [30.56, 30.68, 28.2, 28.78, 28.22, 27.73, 28.01, 28.83, 31.03, 31.38],
    'IC': [22.23, 22.82, 22.53, 20.93, 20.82, 21.05, 20.51, 22.08, 22.68, 23.1]
}

# Create a pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:")
print(df)
print()

# Calculate the mean of each column using NumPy
mean_values = np.mean(df[['SIC', 'AM', 'FE', 'IC']], axis=0)
print("Mean values:")
print(mean_values)
print()

# Calculate the maximum value in the 'SIC' column using pandas
max_sic = df['SIC'].max()
print("Maximum SIC value:")
print(max_sic)
print()

# Sort the DataFrame by the 'RollNo' column in ascending order
sorted_df = df.sort_values('RollNo', ascending=True)
print("Sorted DataFrame:")
print(sorted_df)
print()

# Filter the DataFrame to show only rows where 'AM' is greater than 32
filtered_df = df[df['AM'] > 32]
print("Filtered DataFrame (AM > 32):")
print(filtered_df)
print()

DataFrame:
   RollNo    SIC     AM     FE     IC
0     801  28.48  34.18  30.56  22.23
1     802  28.10  33.72  30.68  22.82
2     803  26.16  31.39  28.20  22.53
3     804  26.16  31.39  28.78  20.93
4     805  26.10  31.32  28.22  20.82
5     806  25.45  30.54  27.73  21.05
6     807  26.16  31.39  28.01  20.51
7     808  27.44  32.93  28.83  22.08
8     809  28.63  34.35  31.03  22.68
9     810  30.35  36.42  31.38  23.10

Mean values:
SIC    27.303
AM     32.763
FE     29.342
IC     21.875
dtype: float64

Maximum SIC value:
30.35

Sorted DataFrame:
   RollNo    SIC     AM     FE     IC
0     801  28.48  34.18  30.56  22.23
1     802  28.10  33.72  30.68  22.82
2     803  26.16  31.39  28.20  22.53
3     804  26.16  31.39  28.78  20.93
4     805  26.10  31.32  28.22  20.82
5     806  25.45  30.54  27.73  21.05
6     807  26.16  31.39  28.01  20.51
7     808  27.44  32.93  28.83  22.08
8     809  28.63  34.35  31.03  22.68
9     810  30.35  36.42  31.38  23.10

Filtered DataFrame (AM

In [ ]:
import numpy as np
array1=np.array(re_array)
print(array1)

#Copy the array
copied_array = array1.copy()

# View the array
view_array = array1.view()

# Modify the copied array
copied_array[0] = 10

# Modify the view array
view_array[0] = 20

# Print the original array
print("Original Array:")
print(array1)

# Print the copied array
print("Copied Array:")
print(copied_array)

# Print the view array
print("View Array:")
print(view_array)

[[28.48 34.18 30.56 22.23 28.1  33.72 30.68 22.82]]
Original Array:
[[20. 20. 20. 20. 20. 20. 20. 20.]]
Copied Array:
[[10. 10. 10. 10. 10. 10. 10. 10.]]
View Array:
[[20. 20. 20. 20. 20. 20. 20. 20.]]


In [ ]:
# Vertical stacking
vertical_stack = np.vstack((array1, copied_array))
print("Vertical Stack:")
print(vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((array1, copied_array))
print("Horizontal Stack:")
print(horizontal_stack)

#searching

target = 71
print("\n searching")
if target in array1:
    print(f"The target element {target} is found in the array.")
else:
    print("The target element is not found in the array.")

# Sorting
sorted_arr = sorted(array1)
print("\nSorting:")
print("Original Array:", array1)
print("Sorted Array:", sorted_arr)

# Counting
count = len(array1)
print("\nCounting:")
print(f"The array contains {count} elements.")

Vertical Stack:
[[20. 20. 20. 20. 20. 20. 20. 20.]
 [10. 10. 10. 10. 10. 10. 10. 10.]]
Horizontal Stack:
[[20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10. 10. 10. 10. 10. 10.]]

 searching
The target element is not found in the array.

Sorting:
Original Array: [[20. 20. 20. 20. 20. 20. 20. 20.]]
Sorted Array: [array([20., 20., 20., 20., 20., 20., 20., 20.])]

Counting:
The array contains 1 elements.
